<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Burak" failures="6" tests="18" name="API Tests" time="7.532" errors="0" timestamp="2025-08-16T23:06:19 TRT">
  <testcase classname="qa.fakestore.tests.CartTests" name="testGetAllCarts" time="1.745"/>
  <testcase classname="qa.fakestore.tests.AuthenticationTests" name="testValidLogin" time="1.757">
    <failure type="java.lang.AssertionError" message="Status code should be 200 expected [200] but found [201]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 expected [200] but found [201]
at qa.fakestore.tests.AuthenticationTests.testValidLogin(AuthenticationTests.java:29)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="qa.fakestore.tests.CartTests" name="testAddNewCart" time="0.349">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;201&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <201>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$4.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$6.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at qa.fakestore.base.BaseTest.validateSuccessResponse(BaseTest.java:42)
at qa.fakestore.tests.CartTests.testAddNewCart(CartTests.java:63)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddNewCart -->
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetAllProducts" time="2.166"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetSingleProduct" time="0.229"/>
  <testcase classname="qa.fakestore.tests.AuthenticationTests" name="testInvalidLogin" time="0.634">
    <failure type="java.lang.AssertionError" message="Status code should be 200 expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 expected [200] but found [401]
at qa.fakestore.tests.AuthenticationTests.testInvalidLogin(AuthenticationTests.java:65)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="qa.fakestore.tests.AuthenticationTests" name="testEmptyCredentials" time="0.227">
    <failure type="java.lang.AssertionError" message="Status code should be 200 expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Status code should be 200 expected [200] but found [400]
at qa.fakestore.tests.AuthenticationTests.testEmptyCredentials(AuthenticationTests.java:96)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testEmptyCredentials -->
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetCategories" time="0.306"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetProductsByCategory" time="0.392"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetProductsByCategory" time="0.323"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetProductsByCategory" time="0.32"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetProductsByCategory" time="0.39"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testAddNewProduct" time="0.302">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;201&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <201>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$4.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$6.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at qa.fakestore.base.BaseTest.validateSuccessResponse(BaseTest.java:42)
at qa.fakestore.tests.ProductAPITests.testAddNewProduct(ProductAPITests.java:126)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testUpdateProduct" time="0.227"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testDeleteProduct" time="0.329"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testGetNonExistentProduct" time="0.224">
    <failure type="java.lang.AssertionError" message="Response should be null for non-existent product expected [null] but found []">
      <![CDATA[java.lang.AssertionError: Response should be null for non-existent product expected [null] but found []
at qa.fakestore.tests.ProductAPITests.testGetNonExistentProduct(ProductAPITests.java:193)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testGetNonExistentProduct -->
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testProductDataIntegrity" time="0.228"/>
  <testcase classname="qa.fakestore.tests.ProductAPITests" name="testAPIPerformance" time="1.061"/>
</testsuite> <!-- API Tests -->
